### PR TITLE
New symbol and gda2020

### PR DESCRIPTION
**Pull request by tengkunuddin**
Hi Neal, 

As discussed in the forum, I have changed a couple of things:
- Used GDA2020 as default datum 
- Changed symbol logic 
- Added new symbol
- Renamed old symbology names to new ones
- Changed mark details with new symbol names

I modified the code in /build as it seemed to be the most complete (/src is outdated?). Will be great if you can compile all of this code for /dist (which I assume is used for the live version of smes-on-the-go)

VS Code gives me a 'Declaration or statement expected error in line 2968' in smes-on-the-go.js. Not too sure what's going on there - would appreciate your help. Sorry I am not able to properly debug the script as I am not been able to load the maps from my local drive.

From this point on, I will start to migrate all of this to our hosted site (with our own Google API code). Will let you know once it's gotten some traction. Thanks again.

### CODE REVIEW

**Review by mrpeel — COMMENTED** [review]
The changes themselves are fine but they've been made in the wrong place.  All changes should be made in the /src directory.  The symbols go in the /src/symbology directory.

The build system for this is quite an old approach - it uses gulp (it runs from the command line).  The workflow is:
 1. make changes to src -> run gulp -> files built to /build & /deploy folder -> changes are served for running & testing locally
2. when the changes are verified run 'gulp deploy' and the files in the /dist directory will be copied to github pages

You'll probably need to update gulp and a bunch of dependencies because the packages are about 4 years old and most of them have updates for vulnerabilities etc.

The last time I upgraded gulp for another project it was quite painful - the code pattern has changed a bit.  

Let me know if you want me to take your changes, apply them and update all the dependencies so that everything works OK.

**Comment by tengkunuddin** [comment]
Thanks for getting back to me with the details. I'm not too familiar with JS so a lot of this build system process is pretty new to me. I'm learning JS from scratch, which is partly the reason why I mentioned that I will take awhile to migrate and extend the current functionality. 

My aim is get the patch working for surveyors in the interim and get them to download GDA2020 coordinates, so I would greatly appreciate if you can take the changes and apply them. Hope it's not too big of a task - thanks again for using your personal time to do this.

**Comment by mrpeel** [comment]
I have made your updates to the src folder and pushed them up separate to this PR.

I've also made a few updates to make sure the gulp component works when using node12.

I haven't done proper testing. To test this locally:
1. Pull the repo down
2. Run 'npm install'
3. Run gulp - it will build and server the file locally (localhost:8080)
4. You can then check if everything is OK.

Once you're happy that everything is OK, I can run the gulp deploy which will send it to the github pages branch and update it for everyone.  It's probably best if I do that, because these components are quite old and there's a good chance it will fail and need something changed (which just happened with the normal build).

**Comment by tengkunuddin** [comment]
Hi Neil, 

Many thanks for helping me compile this. Sorry it took awhile to get back to you - the gulp wasn't compiling before and after many attempts, I realised that I had to downgrade my Node.js to get it to work. It was a good call to get this tested as I found that it's not registering the new symbols. I'll fix this bug and submit a PR when it's good to go.

Cheers, 
Nuddin

**Pull request closed without merging**
